project_id             = "trusty-wavelet-441019-i7"
region                 = "us-west1"
location               = "US"
website_bucket_name    = "rga-sergio-assessment-bucket"
access_logs_bucket_name = "rga-sergio-assessment-access-logs"
