project_id              = "trusty-wavelet-441019-i7"
region                  = "us-west1"
location                = "US"
website_bucket_name     = "rga-sergio-assessment-bucket-${timestamp()}"
access_logs_bucket_name = "rga-sergio-assessment-access-logs-${timestamp()}"
gcp_credentials_file    = "/home/arikatlasrinivasulu/trusty-wavelet-441019-i7-c780b14f875a.json"
index_html_url          = "https://github.com/varahipratyangira/static-html-webpage/raw/main/index.html"
